### PR TITLE
Application Documentation Context and Macros

### PR DESCRIPTION
**Pull request by mvousden**
This changeset adds some context to the application documentation, and incorporates new convenience macros introduced in https://github.com/POETSII/Orchestrator/pull/172.

After an initial attempt (up to `5542499`), I sent the document to GMB to review. His feedback is attached.
[applications_GMB-Comments.pdf](https://github.com/POETSII/orchestrator-documentation/files/6050286/applications_GMB-Comments.pdf)

When approved, I will push the changed document to the shared drive, and create a new minor documentation release.

### CODE REVIEW

**Comment by mvousden** [comment]
(In response to GMB's feedback document above)

Most of the changes I've accepted, except those that follow (and miscellanea):

 - S2.1.1: The <2**32 limit arises due to the Orchestrator data structure and device indexing, I think.

 - S2.1.2.1 "By default, the Softswitch never refuses to accept inbound packets: default behaviour is prioritise receive ahead of everything else." Doesn't that mean, effectively, that we're "dropping" packets (by not sending them?)

 - S2.2.2 "This is an oversimplification. A core can only do one thing at a time, and will only be executing one thread context at a time. e.g. in a fully loaded system, only 1/6th of the threads are computing at any single point in time.": It's intended to be an oversimplification, (even though it's not strictly true depending on how the ALU manifests) - we're just making the point that devices won't all execute magically at the same time.

   Also, nobody is enforcing one thread per core in the design (?!)

 - Amendments to Figure 5. You're right, but I'm honestly just too tired of interfacing with MSWord to change this.

 - S2.2.4.1, I think my grammar is correct
 
 - S2.3 "Technically one DRAM and two SRAMs are shared equally by half of a board" - isn't that the same as what I've said?

 - S3.2 (on splitting the structure over a page) Yeah it sucks. I've tried putting it in a table.

 - I found a Graphs/GraphInstance/Properties element in now-table 1, which I believe to be invalid, so I've removed it.

 - I decided to split the macro table into three smaller tables, so that it's easier for a reader to understand which macros can be used where (to support now-table 4).

**Comment by heliosfa** [comment]
> * S2.1.1: The <2**32 limit arises due to the Orchestrator data structure and device indexing, I think.
Cool, it might be worth just a couple of words to say that it is an Orchestrator limit.

> * S2.1.2.1 "By default, the Softswitch never refuses to accept inbound packets: default behaviour is prioritise receive ahead of everything else." Doesn't that mean, effectively, that we're "dropping" packets (by not sending them?)
That is one way of looking at it, but the packets are never generated (in default mode) or sent eventually (buffering mode), no "packet" has actually been dropped.

> * S2.2.2 "This is an oversimplification. A core can only do one thing at a time, and will only be executing one thread context at a time. e.g. in a fully loaded system, only 1/16th of the threads are computing at any single point in time.": It's intended to be an oversimplification, (even though it's not strictly true depending on how the ALU manifests) - we're just making the point that devices won't all execute magically at the same time.
Fair play, the implication I got from reading was that all of the threads magically executed in parallel (they don't, instructions from each hardware thread are executed sequentially by the core)

>   Also, nobody is enforcing one thread per core in the design (?!)
The core only "deals" with one instruction from one thread at a time and a thread may only appear once in the (8-stage) pipeline. Other things can be off waiting (e.g. FPU, memory read, etc.) while another instruction is dealt with, but it is still only single instruction at a time.

> * Amendments to Figure 5. You're right, but I'm honestly just too tired of interfacing with MSWord to change this.
I could faff with it in Word if you like?

> * S2.2.4.1, I think my grammar is correct
I guess it depends how far we are stretching "just". In the worst case, the could be significant time between indicating that you want to send and OnSend being called (for default), or significant time between staging the packet and it being sent (buffering), if there is congestion.

> * S2.3 "Technically one DRAM and two SRAMs are shared equally by half of a board" - isn't that the same as what I've said?
It's a nuance, what you have written could imply that there is no partitioning and that one core can access either of the DRAMs when in reality it can only access one of them.

**Comment by mvousden** [comment]
So I've made some changes in response to your response (hoho), and emailed you a document to edit should you so please.

**Comment by mvousden** [comment]
I've updated the figure @heliosfa changed - ready for re-review.

**Review by heliosfa — APPROVED** [review]
Whoops, I meant to approve this a while ago. Looks good with that change

**Pull request merged**
